### ISSUE TITLE
The User Registration at Ozwillo 

### ISSUE THREAD

**Issue by iaydogdu** [ozwillo/ozwillo-datacore#102]
We suggest sequential fields for country, province, city/district at Ozwillo.

 

When country is selected from the drop down menu, province field becomes activated with a drop down list of available provinces within that country. And when province is selected, city field gets activated with a drop down list of available cities within that province.

**Comment by mdutoo** [comment]
Thanks. See these query examples in latest release's Playground (now in preprod).
