### ISSUE TITLE
The User Registration at Ozwillo

### ISSUE THREAD

**Issue by iaydogdu** [ozwillo/ozwillo-datacore#103]
The system must allow for a user to register its organization, which is not based in one of the project partners’ countries (France, Italy, Spain, Bulgaria, Turkey).

 

To do that the form can have an selection option like “Is your organisation based in any of the following countries?”

 

•        France

•        Italy

•        Spain

•        Bulgaria

•        Turkey

•        No (other country)

 

And if “no” is selected the province and city fields can become text based strings without autocomplete function or dropdown menu.

**Comment by mdutoo** [comment]
Thanks. Look in geohier:Hierarchical_0 type rather than geoco:Country_0 type to only get countries that are supported by Ozwillo (i.e. by the Portal, apps...). See these query examples in latest release's Playground (now in preprod).
