### ISSUE TITLE
Merging ilçe model and city model at the datacore

### ISSUE THREAD

**Issue by iaydogdu** [ozwillo/ozwillo-datacore#106]
We suggest that we use the conversion table for the management of the sub-divisions in the datacore to reconcile different country cases.

 
Province = İl = Oblast = Provincia

 

City = İlçe = Grad = Ciudad = Citta

 

Therefore we don’t think a seperate İlçe model apart from the City Model; and we suggest you move the İlçe list under the City list. Currently we have made the query pre-selective so that if the resources is of Turkey, query refers to İlçe if not alternative query refers to City.

**Comment by mdutoo** [comment]
Solved since 20151110 release, see how in query examples in 20151120 release.
