### ISSUE TITLE
Playground project dropdown is limited to 20 entries

### ISSUE THREAD

**Issue by mdutoo** [ozwillo/ozwillo-datacore#171]
and alas project portal UI can't be used for those beyond.

**Comment by bobeal** [comment]
Hmm, no, does not seem to be limited (see screenshot) ...

![screen shot 2016-07-05 at 15 49 20](https://cloud.githubusercontent.com/assets/175382/16586860/3fc26a64-42c8-11e6-947d-01dce77a1bf5.png)

**Comment by mdutoo** [comment]
You're right, the coded solution supports as many as 100 projects (but not more for now).

**Comment by mdutoo** [comment]
Actually, the dropdown only displays 20 elements, but the up and down arrows can be used to make the displayed projects go up or down (but the project portal is still displayed only when clicking on it).

**Comment by mdutoo** [comment]
BTW the project portal's own limit is 25 (ex. displayed storage models). Which is less but more than enough for storage models (but less so for pure mixins).
